### ISSUE TITLE
ollie_v2.sh : wrong line endings

### ISSUE THREAD

**Issue by 1r0b1n0** [meatpiHQ/meatpi_ollie_v2#1]
Hi,
I got a small issue when following the setup instruction for Linux (using Ubuntu 22.04) :
`sudo: unable to execute ./ollie_v2.sh: No such file or directory`

The ollie_v2.sh has "DOS style" line endings that makes running the script impossible.
Running `dos2unix ollie_v2.sh` fixed the issue.

**Comment by meatpiHQ** [comment]
@1r0b1n0 Thanks for pointing this out. I'm not sure how this happened.

All fixed now!
